// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: newsfeed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :exec
INSERT INTO Feed (user_feed)
VALUES($1)
`

func (q *Queries) CreateFeed(ctx context.Context, userFeed uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, createFeed, userFeed)
	return err
}
